[package]
name = "modrinth-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = { version = "0.12.4", features = ["blocking","json"] }
serde = { version = "1.0.202", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
