name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    name: Nightly Release (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: windows
            plat: windows
          - os: macos
            plat: darwin
          - os: ubuntu
            plat: linux
      fail-fast: false
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: cargo
      - name: Build
        uses: actions-rs/cargo@v1
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        with:
          command: build
          args: --release

      - name: Rename (linux)
        if: ${{ contains(matrix.os, 'linux') }}
        run: mv target/release/gluon target/release/gluon-${{ matrix.plat }}_amd64

      - name: Rename (windows)
        if: ${{ contains(matrix.os, 'windows') }}
        run: mv target/release/gluon.exe target/release/gluon-${{ matrix.plat }}_amd64.exe

      - name: Rename (macos)
        if: contains(matrix.os, 'macos')
        run: mv target/release/gluon target/release/gluon-${{ matrix.plat }}_arm64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: gluon-${{ matrix.plat }}_amd64
          files: target/release/gluon-*
