[package]
name = "installer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.1"
hex = "0.4.3"
indicatif = "0.17.8"
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["blocking","json"] }
sha1 = "0.10.6"
tokio = { version = "1.38.1", features = ["full"] }
